// EveLens — Character Intelligence for EVE Online
// Copyright © 2006-2021 EVEMon Development Team, © 2025-2026 Alia Collins
// Built with Claude Code (Anthropic)
// Licensed under GPL v2 — see LICENSE for details

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text.Json;
using EveLens.Common.Services;

namespace EveLens.Common.Data
{
    /// <summary>
    /// The SDE-derived SKINR lookup tables: hulls, components, slots, slot configurations,
    /// rarities, point values and tier thresholds. Generated by
    /// <c>tools/generate-skinr-catalog.ps1</c> into <c>Resources/skinr-catalog.json.gz</c>.
    /// </summary>
    /// <remarks>
    /// ESI's SKINR routes carry IDs only, because names are localized — CCP's own words in
    /// the devblog. This catalog is the other half of every SKINR feature: without it a
    /// recipe is eight integers, and with it a recipe is a named, priced, renderable design.
    ///
    /// Two things here are easy to get wrong and expensive to get wrong quietly:
    ///
    /// 1. <see cref="GetSlotToMaterialMap"/> is the ESI-slot → DNA-material-position remap,
    ///    keyed by the hull's faction. It is a bijection, and only the 16 factions that ship
    ///    their own hulls have an entry; the rest are identity and CCP omits them. Skipping
    ///    it does not throw — it renders the right four colours in the wrong four places,
    ///    which looks like a working feature.
    /// 2. <see cref="GetTierThresholds"/> is keyed by <c>shipTreeGroupID</c>, not by the
    ///    inventory <c>groupID</c>. The two keyspaces overlap numerically, so a mixup
    ///    silently returns another hull class's thresholds.
    ///
    /// Loading is lazy, best-effort and never throws: a missing or corrupt datafile yields
    /// <see cref="IsAvailable"/> = false, which the SKINR UI surfaces as "static data
    /// unavailable" rather than crashing a tab. Same posture as
    /// <see cref="StaticTranslations"/>, which this deliberately mirrors.
    ///
    /// Production: <c>SkinrRecipeResolver</c> holds one instance via <c>AppServices</c>.
    /// Testing: <see cref="FromJson"/> builds one from an inline JSON string, no file needed.
    /// </remarks>
    public sealed class SkinrCatalog
    {
        /// <summary>
        /// The generator's schema version this code understands. A newer catalog is rejected
        /// rather than half-read: a field rename would otherwise present as missing data.
        /// </summary>
        public const int SupportedSchemaVersion = 1;

        private const string DatafileName = "skinr-catalog.json.gz";

        private readonly Dictionary<int, SkinrHull> _hulls;
        private readonly Dictionary<int, SkinrComponent> _components;
        private readonly Dictionary<int, SkinrSlotDefinition> _slots;
        private readonly Dictionary<int, SkinrSlotConfiguration> _slotConfigurations;
        private readonly Dictionary<int, SkinrRarity> _rarities;
        private readonly Dictionary<int, SkinrText> _componentCategories;
        private readonly Dictionary<int, Dictionary<int, int>> _slotsToMaterials;
        private readonly Dictionary<int, Dictionary<int, int>> _pointValues;
        private readonly Dictionary<int, Dictionary<int, int>> _tierThresholds;

        /// <summary>
        /// Ship type ID → the slot configuration that governs it. Precomputed at load because
        /// the alternative is scanning four ship lists (one of them 85 entries) per lookup,
        /// and the SKINR browser does this per row.
        /// </summary>
        private readonly Dictionary<int, int> _shipToConfiguration;

        private static readonly Dictionary<int, int> s_identitySlotMap =
            new() { [1] = 1, [2] = 2, [3] = 3, [4] = 4 };

        private SkinrCatalog()
        {
            _hulls = new Dictionary<int, SkinrHull>();
            _components = new Dictionary<int, SkinrComponent>();
            _slots = new Dictionary<int, SkinrSlotDefinition>();
            _slotConfigurations = new Dictionary<int, SkinrSlotConfiguration>();
            _rarities = new Dictionary<int, SkinrRarity>();
            _componentCategories = new Dictionary<int, SkinrText>();
            _slotsToMaterials = new Dictionary<int, Dictionary<int, int>>();
            _pointValues = new Dictionary<int, Dictionary<int, int>>();
            _tierThresholds = new Dictionary<int, Dictionary<int, int>>();
            _shipToConfiguration = new Dictionary<int, int>();
            SdeBuild = string.Empty;
        }

        /// <summary>An empty catalog. Every lookup misses; nothing throws.</summary>
        public static SkinrCatalog Empty { get; } = new();

        /// <summary>True when the datafile loaded and contained hulls and components.</summary>
        public bool IsAvailable => _hulls.Count > 0 && _components.Count > 0;

        /// <summary>Schema version of the loaded datafile.</summary>
        public int SchemaVersion { get; private set; }

        /// <summary>The SDE build the catalog was generated from, e.g. <c>3470007</c>.</summary>
        public string SdeBuild { get; private set; }

        /// <summary>When the catalog was generated, UTC. Default when unavailable.</summary>
        public DateTime GeneratedUtc { get; private set; }

        public IReadOnlyDictionary<int, SkinrHull> Hulls => _hulls;
        public IReadOnlyDictionary<int, SkinrComponent> Components => _components;
        public IReadOnlyDictionary<int, SkinrSlotDefinition> Slots => _slots;
        public IReadOnlyDictionary<int, SkinrSlotConfiguration> SlotConfigurations => _slotConfigurations;
        public IReadOnlyDictionary<int, SkinrRarity> Rarities => _rarities;
        public IReadOnlyDictionary<int, SkinrText> ComponentCategories => _componentCategories;

        // ------------------------------------------------------------------
        // Loading
        // ------------------------------------------------------------------

        /// <summary>
        /// Loads the bundled catalog, searching the same candidate paths as the SDE
        /// translation datafiles. Returns <see cref="Empty"/> rather than throwing when the
        /// file is absent or unreadable — SKINR is one feature, not a startup dependency.
        /// </summary>
        public static SkinrCatalog Load()
        {
            foreach (string path in CandidatePaths())
            {
                try
                {
                    if (!File.Exists(path))
                        continue;

                    using FileStream stream = File.OpenRead(path);
                    using var gzip = new GZipStream(stream, CompressionMode.Decompress);
                    SkinrCatalog catalog = FromStream(gzip);

                    AppServices.TraceService?.Trace(
                        $"Loaded SKINR catalog (SDE {catalog.SdeBuild}): {catalog.Hulls.Count} hulls, " +
                        $"{catalog.Components.Count} components from {path}");
                    return catalog;
                }
                catch (Exception ex)
                {
                    AppServices.TraceService?.Trace($"Failed to load SKINR catalog from {path}: {ex.Message}");
                }
            }

            AppServices.TraceService?.Trace(
                $"SKINR catalog {DatafileName} not found; SKINR names and rendering are unavailable.");
            return Empty;
        }

        private static IEnumerable<string> CandidatePaths()
        {
            string? datafiles = null;
            try { datafiles = Datafile.GetDatafilesDirectory(); } catch { /* not initialised yet */ }
            if (!string.IsNullOrEmpty(datafiles))
                yield return Path.Combine(datafiles, DatafileName);

            yield return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resources", DatafileName);

            string? appData = null;
            try { appData = AppServices.ApplicationPaths?.DataDirectory; } catch { /* ditto */ }
            if (!string.IsNullOrEmpty(appData))
                yield return Path.Combine(appData, DatafileName);
        }

        /// <summary>Parses a catalog from raw (already decompressed) UTF-8 JSON.</summary>
        public static SkinrCatalog FromStream(Stream utf8Json)
        {
            using JsonDocument doc = JsonDocument.Parse(utf8Json);
            return FromDocument(doc);
        }

        /// <summary>Parses a catalog from a JSON string. For tests and tooling.</summary>
        public static SkinrCatalog FromJson(string json)
        {
            using JsonDocument doc = JsonDocument.Parse(json);
            return FromDocument(doc);
        }

        private static SkinrCatalog FromDocument(JsonDocument doc)
        {
            JsonElement root = doc.RootElement;
            var catalog = new SkinrCatalog
            {
                SchemaVersion = GetInt(root, "schemaVersion", 0),
                SdeBuild = GetString(root, "sdeBuild") ?? string.Empty
            };

            if (catalog.SchemaVersion > SupportedSchemaVersion)
                throw new NotSupportedException(
                    $"SKINR catalog schema {catalog.SchemaVersion} is newer than the supported " +
                    $"{SupportedSchemaVersion}. Update EveLens rather than reading it partially.");

            string? generated = GetString(root, "generatedUtc");
            if (generated != null && DateTime.TryParse(generated, CultureInfo.InvariantCulture,
                    DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out DateTime gen))
                catalog.GeneratedUtc = gen;

            catalog.ReadSlots(root);
            catalog.ReadSlotConfigurations(root);
            catalog.ReadSlotsToMaterials(root);
            catalog.ReadCategoriesAndRarities(root);
            catalog.ReadIntMatrix(root, "componentPointValues", catalog._pointValues);
            catalog.ReadIntMatrix(root, "tierThresholds", catalog._tierThresholds);
            catalog.ReadComponents(root);
            catalog.ReadHulls(root);
            return catalog;
        }

        private void ReadSlots(JsonElement root)
        {
            foreach ((int id, JsonElement e) in IntKeyed(root, "slots"))
            {
                _slots[id] = new SkinrSlotDefinition(
                    id,
                    GetString(e, "name") ?? string.Empty,
                    GetInt(e, "category", 0),
                    ReadIntList(e, "allowedComponents"),
                    SkinrText.From(e, "displayName"));
            }
        }

        private void ReadSlotConfigurations(JsonElement root)
        {
            foreach ((int id, JsonElement e) in IntKeyed(root, "slotConfigurations"))
            {
                _slotConfigurations[id] = new SkinrSlotConfiguration(
                    id,
                    GetString(e, "name") ?? string.Empty,
                    GetInt(e, "priority", int.MaxValue),
                    GetBool(e, "allowAllShips"),
                    ReadIntList(e, "slots"),
                    ReadIntList(e, "ships"));
            }

            // Lowest priority number wins — configuration 6 "No custom skins allowed" is
            // priority 0 and must beat the priority-3 allow-all default. Assign each ship
            // once, in priority order, so the first (most specific) claim sticks.
            foreach (SkinrSlotConfiguration cfg in _slotConfigurations.Values
                         .Where(c => !c.AllowAllShips)
                         .OrderBy(c => c.Priority))
            {
                foreach (int shipTypeId in cfg.Ships)
                    _shipToConfiguration.TryAdd(shipTypeId, cfg.Id);
            }
        }

        private void ReadSlotsToMaterials(JsonElement root)
        {
            foreach ((int factionId, JsonElement e) in IntKeyed(root, "slotsToMaterials"))
            {
                var map = new Dictionary<int, int>();
                foreach (JsonProperty p in e.EnumerateObject())
                {
                    if (int.TryParse(p.Name, NumberStyles.Integer, CultureInfo.InvariantCulture, out int slot))
                        map[slot] = p.Value.GetInt32();
                }
                _slotsToMaterials[factionId] = map;
            }
        }

        private void ReadCategoriesAndRarities(JsonElement root)
        {
            foreach ((int id, JsonElement e) in IntKeyed(root, "componentCategories"))
                _componentCategories[id] = SkinrText.FromValue(e);

            foreach ((int id, JsonElement e) in IntKeyed(root, "componentRarities"))
                _rarities[id] = new SkinrRarity(id, GetInt(e, "rank", id), SkinrText.From(e, "name"));
        }

        private void ReadIntMatrix(JsonElement root, string property, Dictionary<int, Dictionary<int, int>> into)
        {
            foreach ((int outer, JsonElement e) in IntKeyed(root, property))
            {
                var inner = new Dictionary<int, int>();
                foreach (JsonProperty p in e.EnumerateObject())
                {
                    if (int.TryParse(p.Name, NumberStyles.Integer, CultureInfo.InvariantCulture, out int k))
                        inner[k] = p.Value.GetInt32();
                }
                into[outer] = inner;
            }
        }

        private void ReadComponents(JsonElement root)
        {
            foreach ((int id, JsonElement e) in IntKeyed(root, "components"))
            {
                SkinrSequenceBinder? binder = null;
                if (e.TryGetProperty("sequenceBinder", out JsonElement sb) && sb.ValueKind == JsonValueKind.Object)
                    binder = new SkinrSequenceBinder(GetInt(sb, "itemTypeID", 0), GetInt(sb, "count", 0));

                var associated = new List<SkinrAssociatedType>();
                if (e.TryGetProperty("associatedTypes", out JsonElement at) && at.ValueKind == JsonValueKind.Array)
                {
                    foreach (JsonElement item in at.EnumerateArray())
                        associated.Add(new SkinrAssociatedType(
                            GetInt(item, "typeID", 0), GetInt(item, "licenseUsesGranted", 0)));
                }

                _components[id] = new SkinrComponent(
                    id,
                    SkinrText.From(e, "name"),
                    GetInt(e, "category", 0),
                    GetInt(e, "rarity", 0),
                    GetString(e, "finish") ?? string.Empty,
                    GetString(e, "resourceFile") ?? string.Empty,
                    GetString(e, "dnaToken") ?? string.Empty,
                    GetString(e, "iconFile") ?? string.Empty,
                    GetString(e, "projectionTypeU") ?? string.Empty,
                    GetString(e, "projectionTypeV") ?? string.Empty,
                    GetBool(e, "published"),
                    binder,
                    associated);
            }
        }

        private void ReadHulls(JsonElement root)
        {
            foreach ((int id, JsonElement e) in IntKeyed(root, "hulls"))
            {
                _hulls[id] = new SkinrHull(
                    id,
                    SkinrText.From(e, "name"),
                    GetInt(e, "groupID", 0),
                    SkinrText.From(e, "groupName"),
                    GetInt(e, "graphicID", 0),
                    GetNullableInt(e, "factionID"),
                    GetNullableInt(e, "shipTreeGroupID"),
                    GetNullableInt(e, "raceID"),
                    GetNullableInt(e, "metaGroupID"),
                    GetNullableInt(e, "marketGroupID"),
                    GetDouble(e, "radius"),
                    GetBool(e, "published"),
                    GetString(e, "sofHullName") ?? string.Empty,
                    GetString(e, "sofFactionName") ?? string.Empty,
                    GetString(e, "sofRaceName") ?? string.Empty,
                    GetNullableInt(e, "sofMaterialSetID"));
            }
        }

        // ------------------------------------------------------------------
        // Lookups
        // ------------------------------------------------------------------

        public SkinrHull? GetHull(int shipTypeId) =>
            _hulls.TryGetValue(shipTypeId, out SkinrHull? hull) ? hull : null;

        public SkinrComponent? GetComponent(int componentId) =>
            _components.TryGetValue(componentId, out SkinrComponent? c) ? c : null;

        public SkinrSlotDefinition? GetSlot(int slotId) =>
            _slots.TryGetValue(slotId, out SkinrSlotDefinition? s) ? s : null;

        /// <summary>
        /// The ESI-slot → DNA-material-position remap for a hull's faction. Absent factions
        /// are identity: CCP only authors an entry for the 16 factions that ship their own
        /// hulls, so "no entry" means "no reordering", not "unknown".
        /// </summary>
        public IReadOnlyDictionary<int, int> GetSlotToMaterialMap(int? factionId)
        {
            if (factionId.HasValue &&
                _slotsToMaterials.TryGetValue(factionId.Value, out Dictionary<int, int>? map))
                return map;
            return s_identitySlotMap;
        }

        /// <summary>
        /// The slot configuration governing a hull. Never null: the allow-all default is the
        /// floor. A hull in configuration 6 legitimately has zero slots — "no custom skins
        /// allowed" is an answer, not a failure.
        /// </summary>
        public SkinrSlotConfiguration GetSlotConfiguration(int shipTypeId)
        {
            if (_shipToConfiguration.TryGetValue(shipTypeId, out int cfgId) &&
                _slotConfigurations.TryGetValue(cfgId, out SkinrSlotConfiguration? specific))
                return specific;

            SkinrSlotConfiguration? fallback = _slotConfigurations.Values
                .Where(c => c.AllowAllShips)
                .OrderBy(c => c.Priority)
                .FirstOrDefault();

            return fallback ?? SkinrSlotConfiguration.Unknown;
        }

        /// <summary>Design points a component contributes, by its category and rarity.</summary>
        public int GetPointValue(int categoryId, int rarityId) =>
            _pointValues.TryGetValue(categoryId, out Dictionary<int, int>? byRarity) &&
            byRarity.TryGetValue(rarityId, out int points)
                ? points
                : 0;

        /// <summary>
        /// Tier → minimum design points for a ship-tree group. Empty for the three groups
        /// CCP excludes from SKINR entirely (Strategic Cruiser, Tactical Destroyer, Capsule).
        /// </summary>
        public IReadOnlyDictionary<int, int> GetTierThresholds(int? shipTreeGroupId)
        {
            if (shipTreeGroupId.HasValue &&
                _tierThresholds.TryGetValue(shipTreeGroupId.Value, out Dictionary<int, int>? t))
                return t;
            return new Dictionary<int, int>();
        }

        /// <summary>
        /// The highest tier a design's point total reaches for a hull's ship-tree group, or
        /// 0 when the group has no thresholds. ESI hands us <c>tier.level</c> outright, so
        /// this exists to cross-check the catalog and to price a design a player is planning
        /// but has not built.
        /// </summary>
        public int GetTierForPoints(int? shipTreeGroupId, int designPoints)
        {
            int tier = 0;
            foreach (KeyValuePair<int, int> kv in GetTierThresholds(shipTreeGroupId))
            {
                if (designPoints >= kv.Value && kv.Key > tier)
                    tier = kv.Key;
            }
            return tier;
        }

        /// <summary>Design points still needed to reach the next tier, or null at the cap.</summary>
        public int? GetPointsToNextTier(int? shipTreeGroupId, int designPoints)
        {
            int? best = null;
            foreach (KeyValuePair<int, int> kv in GetTierThresholds(shipTreeGroupId))
            {
                if (kv.Value > designPoints && (best == null || kv.Value < best.Value))
                    best = kv.Value;
            }
            return best - designPoints;
        }

        // ------------------------------------------------------------------
        // JSON helpers
        // ------------------------------------------------------------------

        private static IEnumerable<(int Key, JsonElement Value)> IntKeyed(JsonElement root, string property)
        {
            if (!root.TryGetProperty(property, out JsonElement obj) || obj.ValueKind != JsonValueKind.Object)
                yield break;

            foreach (JsonProperty p in obj.EnumerateObject())
            {
                if (int.TryParse(p.Name, NumberStyles.Integer, CultureInfo.InvariantCulture, out int key))
                    yield return (key, p.Value);
            }
        }

        private static List<int> ReadIntList(JsonElement e, string property)
        {
            var list = new List<int>();
            if (e.TryGetProperty(property, out JsonElement arr) && arr.ValueKind == JsonValueKind.Array)
            {
                foreach (JsonElement item in arr.EnumerateArray())
                {
                    if (item.ValueKind == JsonValueKind.Number)
                        list.Add(item.GetInt32());
                }
            }
            return list;
        }

        private static string? GetString(JsonElement e, string property) =>
            e.TryGetProperty(property, out JsonElement v) && v.ValueKind == JsonValueKind.String
                ? v.GetString()
                : null;

        private static int GetInt(JsonElement e, string property, int fallback) =>
            e.TryGetProperty(property, out JsonElement v) && v.ValueKind == JsonValueKind.Number
                ? v.GetInt32()
                : fallback;

        private static int? GetNullableInt(JsonElement e, string property) =>
            e.TryGetProperty(property, out JsonElement v) && v.ValueKind == JsonValueKind.Number
                ? v.GetInt32()
                : null;

        private static double GetDouble(JsonElement e, string property) =>
            e.TryGetProperty(property, out JsonElement v) && v.ValueKind == JsonValueKind.Number
                ? v.GetDouble()
                : 0d;

        private static bool GetBool(JsonElement e, string property) =>
            e.TryGetProperty(property, out JsonElement v) && v.ValueKind == JsonValueKind.True;
    }

    /// <summary>
    /// A catalog string in every language the app ships. SKINR component and slot names exist
    /// nowhere else — unlike type and group names, which <see cref="StaticTranslations"/>
    /// loads from the per-language SDE datafiles — so the catalog carries them inline.
    /// </summary>
    public sealed class SkinrText
    {
        private static readonly Dictionary<string, string> s_none = new();

        private readonly Dictionary<string, string> _byLanguage;

        private SkinrText(Dictionary<string, string> byLanguage) => _byLanguage = byLanguage;

        public static SkinrText None { get; } = new(s_none);

        /// <summary>The English name. Always the fallback, never empty for real records.</summary>
        public string English => _byLanguage.TryGetValue("en", out string? en) ? en : string.Empty;

        /// <summary>
        /// The name to display now: the current UI language when translated game names are in
        /// effect, English otherwise. Goes through the same policy gate as every other game
        /// name so a Korean player who prefers English item names gets English here too.
        /// </summary>
        public string Localized
        {
            get
            {
                if (!StaticTranslations.UseLocalizedGameNames)
                    return English;
                string translated = Get(Loc.Language);
                return string.IsNullOrEmpty(translated) ? English : translated;
            }
        }

        /// <summary>Raw table lookup for an explicit language. Empty when absent.</summary>
        public string Get(string language) =>
            _byLanguage.TryGetValue(language, out string? value) ? value : string.Empty;

        public override string ToString() => Localized;

        internal static SkinrText From(JsonElement parent, string property) =>
            parent.TryGetProperty(property, out JsonElement e) ? FromValue(e) : None;

        internal static SkinrText FromValue(JsonElement e)
        {
            // The generator emits a per-language object for names, but plain strings for
            // untranslated engineering keys like componentCategories. Accept both so one
            // reader covers the whole catalog.
            if (e.ValueKind == JsonValueKind.String)
                return new SkinrText(new Dictionary<string, string> { ["en"] = e.GetString() ?? string.Empty });

            if (e.ValueKind != JsonValueKind.Object)
                return None;

            var map = new Dictionary<string, string>();
            foreach (JsonProperty p in e.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.String)
                    map[p.Name] = p.Value.GetString() ?? string.Empty;
            }
            return map.Count == 0 ? None : new SkinrText(map);
        }
    }

    /// <summary>A ship hull that can wear a SKINR, joined from types + graphics.</summary>
    public sealed class SkinrHull
    {
        internal SkinrHull(int typeId, SkinrText name, int groupId, SkinrText groupName, int graphicId,
            int? factionId, int? shipTreeGroupId, int? raceId, int? metaGroupId, int? marketGroupId,
            double radius, bool published, string sofHullName, string sofFactionName, string sofRaceName,
            int? sofMaterialSetId)
        {
            TypeId = typeId;
            Name = name;
            GroupId = groupId;
            GroupName = groupName;
            GraphicId = graphicId;
            FactionId = factionId;
            ShipTreeGroupId = shipTreeGroupId;
            RaceId = raceId;
            MetaGroupId = metaGroupId;
            MarketGroupId = marketGroupId;
            Radius = radius;
            Published = published;
            SofHullName = sofHullName;
            SofFactionName = sofFactionName;
            SofRaceName = sofRaceName;
            SofMaterialSetId = sofMaterialSetId;
        }

        public int TypeId { get; }
        public SkinrText Name { get; }
        public int GroupId { get; }
        public SkinrText GroupName { get; }
        public int GraphicId { get; }

        /// <summary>Drives the ESI-slot → DNA-material remap. Null on NPC-only hulls.</summary>
        public int? FactionId { get; }

        /// <summary>Keys the tier thresholds. NOT the inventory group ID.</summary>
        public int? ShipTreeGroupId { get; }

        public int? RaceId { get; }
        public int? MetaGroupId { get; }
        public int? MarketGroupId { get; }
        public double Radius { get; }
        public bool Published { get; }

        /// <summary>SOF hull name, e.g. <c>mf4_t1</c> for the Rifter. First DNA token.</summary>
        public string SofHullName { get; }

        /// <summary>SOF faction name, e.g. <c>minmatarbase</c>. Second DNA token.</summary>
        public string SofFactionName { get; }

        /// <summary>SOF race name, e.g. <c>minmatar</c>. Third DNA token.</summary>
        public string SofRaceName { get; }

        public int? SofMaterialSetId { get; }

        /// <summary>True when all three SOF tokens resolved, i.e. the hull is renderable.</summary>
        public bool HasSofIdentity =>
            !string.IsNullOrEmpty(SofHullName) &&
            !string.IsNullOrEmpty(SofFactionName) &&
            !string.IsNullOrEmpty(SofRaceName);

        public override string ToString() => $"{Name.English} ({TypeId})";
    }

    /// <summary>A nanocoating, pattern or metallic component from <c>skinrComponents</c>.</summary>
    public sealed class SkinrComponent
    {
        internal SkinrComponent(int id, SkinrText name, int categoryId, int rarityId, string finish,
            string resourceFile, string dnaToken, string iconFile, string projectionTypeU,
            string projectionTypeV, bool published, SkinrSequenceBinder? sequenceBinder,
            IReadOnlyList<SkinrAssociatedType> associatedTypes)
        {
            Id = id;
            Name = name;
            CategoryId = categoryId;
            RarityId = rarityId;
            Finish = finish;
            ResourceFile = resourceFile;
            DnaToken = dnaToken;
            IconFile = iconFile;
            ProjectionTypeU = projectionTypeU;
            ProjectionTypeV = projectionTypeV;
            Published = published;
            SequenceBinder = sequenceBinder;
            AssociatedTypes = associatedTypes;
        }

        public int Id { get; }
        public SkinrText Name { get; }

        /// <summary>1 Material, 2 Pattern, 3 Metallic — see <see cref="SkinrCatalog.ComponentCategories"/>.</summary>
        public int CategoryId { get; }

        /// <summary>1 Standard … 6 Empyrean.</summary>
        public int RarityId { get; }

        /// <summary>Matte, Satin or Gloss.</summary>
        public string Finish { get; }

        /// <summary>
        /// The engine resource. A <c>.red</c> material for categories 1 and 3; a <c>.dds</c>
        /// projection texture for category 2, which is what a pattern mask samples.
        /// </summary>
        public string ResourceFile { get; }

        /// <summary>
        /// The SOF DNA material token — <see cref="ResourceFile"/>'s basename with
        /// <c>.red</c> stripped. Meaningful for material categories only; a pattern is not
        /// addressed by DNA at all, it is a custom mask over a texture.
        /// </summary>
        public string DnaToken { get; }

        public string IconFile { get; }

        /// <summary>Horizontal wrap mode: <c>clamp-to-border</c>, <c>clamp-to-edge</c> or <c>repeat</c>.</summary>
        public string ProjectionTypeU { get; }

        /// <summary>Vertical wrap mode, same domain.</summary>
        public string ProjectionTypeV { get; }

        public bool Published { get; }

        /// <summary>The in-game item and quantity that yields this component.</summary>
        public SkinrSequenceBinder? SequenceBinder { get; }

        /// <summary>
        /// Item types that grant a license for this component. <c>licenseUsesGranted</c> of
        /// -1 means unlimited, which is how permanent unlocks are expressed.
        /// </summary>
        public IReadOnlyList<SkinrAssociatedType> AssociatedTypes { get; }

        public bool IsPattern => CategoryId == SkinrComponentCategory.Pattern;
        public bool IsMaterial => CategoryId is SkinrComponentCategory.Material or SkinrComponentCategory.Metallic;

        public override string ToString() => $"{Name.English} ({Id})";
    }

    /// <summary>Component category IDs from <c>skinrComponentCategories</c>.</summary>
    public static class SkinrComponentCategory
    {
        public const int Material = 1;
        public const int Pattern = 2;
        public const int Metallic = 3;
    }

    /// <summary>
    /// SKINR slot IDs. These are ESI's <c>layout.slots[].id</c> values and the stable key for
    /// everything downstream, so they are named rather than scattered as literals.
    /// </summary>
    public static class SkinrSlot
    {
        public const int PrimaryNanocoating = 1;
        public const int SecondaryNanocoating = 2;
        public const int TertiaryNanocoating = 3;
        public const int TechArea = 4;
        public const int Pattern = 5;
        public const int PatternMaterial = 6;
        public const int SecondaryPattern = 7;
        public const int SecondaryPatternMaterial = 8;

        /// <summary>The four slots the faction remap applies to.</summary>
        public static readonly int[] NanocoatingSlots =
            { PrimaryNanocoating, SecondaryNanocoating, TertiaryNanocoating, TechArea };

        /// <summary>Pattern slot paired with the slot holding the material it is painted in.</summary>
        public static int MaterialSlotForPattern(int patternSlot) => patternSlot switch
        {
            Pattern => PatternMaterial,
            SecondaryPattern => SecondaryPatternMaterial,
            _ => 0
        };
    }

    public sealed class SkinrSlotDefinition
    {
        internal SkinrSlotDefinition(int id, string name, int categoryId,
            IReadOnlyList<int> allowedComponentCategories, SkinrText displayName)
        {
            Id = id;
            Name = name;
            CategoryId = categoryId;
            AllowedComponentCategories = allowedComponentCategories;
            DisplayName = displayName;
        }

        public int Id { get; }

        /// <summary>The engineering key, e.g. <c>secondary_nanocoating</c>. Never localized.</summary>
        public string Name { get; }

        /// <summary>1 Material_slot, 2 Pattern_slot, 3 Pattern_material_slot.</summary>
        public int CategoryId { get; }

        public IReadOnlyList<int> AllowedComponentCategories { get; }

        /// <summary>The player-facing name, e.g. "Detailing Slot" for slot 3.</summary>
        public SkinrText DisplayName { get; }

        public override string ToString() => $"{Name} ({Id})";
    }

    /// <summary>
    /// Which of the eight slots a hull actually offers. Priority orders specificity: lower
    /// wins, and the allow-all default sits at the bottom.
    /// </summary>
    public sealed class SkinrSlotConfiguration
    {
        internal SkinrSlotConfiguration(int id, string name, int priority, bool allowAllShips,
            IReadOnlyList<int> slots, IReadOnlyList<int> ships)
        {
            Id = id;
            Name = name;
            Priority = priority;
            AllowAllShips = allowAllShips;
            Slots = slots;
            Ships = ships;
        }

        /// <summary>
        /// Used when the catalog is unavailable. Deliberately permissive: with no static data
        /// we cannot know a hull is restricted, and refusing every slot would look like the
        /// hull allows no skins at all.
        /// </summary>
        public static SkinrSlotConfiguration Unknown { get; } = new(
            0, "Unknown", int.MaxValue, true, new[] { 1, 2, 3, 4, 5, 6, 7, 8 }, Array.Empty<int>());

        public int Id { get; }
        public string Name { get; }
        public int Priority { get; }
        public bool AllowAllShips { get; }
        public IReadOnlyList<int> Slots { get; }
        public IReadOnlyList<int> Ships { get; }

        /// <summary>True for configuration 6: the hull cannot be customized at all.</summary>
        public bool ForbidsCustomization => Slots.Count == 0;

        public bool Allows(int slotId) => Slots.Contains(slotId);

        public override string ToString() => $"{Name} ({Id})";
    }

    public sealed class SkinrRarity
    {
        internal SkinrRarity(int id, int rank, SkinrText name)
        {
            Id = id;
            Rank = rank;
            Name = name;
        }

        public int Id { get; }
        public int Rank { get; }
        public SkinrText Name { get; }

        public override string ToString() => Name.English;
    }

    /// <summary>The item type and quantity that produce a component.</summary>
    public sealed class SkinrSequenceBinder
    {
        internal SkinrSequenceBinder(int itemTypeId, int count)
        {
            ItemTypeId = itemTypeId;
            Count = count;
        }

        public int ItemTypeId { get; }
        public int Count { get; }
    }

    /// <summary>An item type granting a component license. -1 uses means unlimited.</summary>
    public sealed class SkinrAssociatedType
    {
        internal SkinrAssociatedType(int typeId, int licenseUsesGranted)
        {
            TypeId = typeId;
            LicenseUsesGranted = licenseUsesGranted;
        }

        public int TypeId { get; }
        public int LicenseUsesGranted { get; }
        public bool IsUnlimited => LicenseUsesGranted < 0;
    }
}
