// EVEMon NexT — Character Intelligence for EVE Online
// Copyright © 2006-2021 EVEMon Development Team, © 2025-2026 Alia Collins
// Built with Claude Code (Anthropic)
// Licensed under GPL v2 — see LICENSE for details

namespace EVEMon.Common.Services
{
    /// <summary>
    /// Compile-time build metadata embedded into the binary.
    /// Referenced by the diagnostic TCP stream, crash reports, log files,
    /// and the About window. Every trace output carries this fingerprint.
    /// </summary>
    public static class BuildInfo
    {
        public const string ProductName = "EVEMon NexT";
        public const string Tagline = "Character Intelligence for EVE Online";
        public const string Website = "https://evemon.dev";
        public const string Repository = "https://github.com/aliacollins/evemon";
        public const string Copyright = "Copyright \u00a9 2006-2021 EVEMon Development Team, \u00a9 2025-2026 Alia Collins";
        public const string License = "GPL v2";

        /// <summary>
        /// One-line footer used in plan exports, clipboard copies, and file outputs.
        /// </summary>
        public const string ExportFooter = "Generated by EVEMon NexT (evemon.dev)";

        /// <summary>
        /// Generator tag written into settings files.
        /// </summary>
        public const string SettingsGenerator = "EVEMon NexT";

        /// <summary>
        /// Status bar text shown in every window.
        /// </summary>
        public static string StatusBarText
        {
            get
            {
                string version = AppServices.FileVersionInfo?.ProductVersion ?? "1.0.0";
                return $"EVEMon NexT {version} | evemon.dev | \u00a9 2026 Alia Collins | GPL v2";
            }
        }
    }
}
